### PR TITLE
avoid ambiguity created between std::advance and boost::advance; fixes #845

### LINKED ISSUE #845: call to 'advance' is ambiguous
When I use the `accumulate` algorithm in my project I get the following error:
```
In file included from /home/XXX/Projects/kylec/src/analysis/lookup/FunctionLookup.cpp:1:
In file included from /home/XXX/Projects/kylec/include/analysis/convertability/CastConvertability.hpp:3:
In file included from /home/XXX/Projects/kylec/include/analysis/convertability/GenericConvertability.hpp:11:
In file included from /home/XXX/Projects/kylec/external/range_v3/include/range/v3/all.hpp:17:
In file included from /home/XXX/Projects/kylec/external/range_v3/include/range/v3/core.hpp:17:
In file included from /home/XXX/Projects/kylec/external/range_v3/include/range/v3/begin_end.hpp:27:
/home/XXX/Projects/kylec/external/range_v3/include/range/v3/utility/iterator.hpp:112:21: error: call to 'advance' is ambiguous
                    advance(i, n);
```

candidates are:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/bits/stl_iterator_base_funcs.h:194:5: note: candidate function [with _InputIterator = __gnu_cxx::__normal_iterator<const ~LongLongType~, _Distance = long]
    advance(_InputIterator& __i, _Distance __n)
```

and 

```
/usr/include/boost/iterator/advance.hpp:68:9: note: candidate function [with InputIterator = __gnu_cxx::__normal_iterator<const ~LongLongType~, Distance = long]
        advance(InputIterator& it, Distance n)
```
I dont realy know if I accidentialy populated the namespace, but if not this could be easily fixed

### PR DESCRIPTION
**Pull request by ericniebler**

### CODE REVIEW

File: test/utility/iterator.cpp [hunk 1]
```diff
@@ -157,6 +158,19 @@ CONCEPT_ASSERT(IndirectlyMovable<int const *, int *>());
...
+{
+    struct my_dummy{}; // just to have a type from boost namespace
+}
+
+// Regression test for https://github.com/ericniebler/range-v3/issues/845
+void test_845()
+{
+    std::list<boost::my_dummy> v = { boost::my_dummy{} };
+    auto itr = v.begin();
+    ranges::advance(itr, 1); // Should not create ambiguity
```
Comment (CaseyCarter) [inline test/utility/iterator.cpp]: This would be a much more useful test if we use the namespace `notboost`, and put a conflicting definition of `advance` in it.

File: include/range/v3/utility/iterator.hpp [hunk 2]
```diff
@@ -109,7 +87,7 @@ namespace ranges
                 {
                     // Use ADL here to give custom iterator types (like counted_iterator)
                     // a chance to optimize it (see utility/counted_iterator.hpp)
```
Comment (CaseyCarter) [inline include/range/v3/utility/iterator.hpp]: This comment has bitrotted - we should remove it.
