### PR TITLE
Fix #839 macro to the clang version for MacOs

### LINKED ISSUE #839: [meta] detail::find_if_ breaks on apple clang
recently @CaseyCarter added

```
#if defined(__clang__) && __clang_major__ < 6
                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
                static constexpr bool s_v[sizeof...(List)] = {invoke<Fun, List>::type::value...};
#else
                static constexpr bool s_v[] = {invoke<Fun, List>::type::value...};
#endif
```

But this fails with apples clang:

```
clang++ --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

where `___clang_major__` is `9`.

### PR DESCRIPTION
**Pull request by maikel**
This should fix #839

### CODE REVIEW

**Comment by johelegp** [comment]
For future reference, you could have reused the other pull request by force pushing the changes, i.e., `git push -f`.

File: include/meta/meta.hpp [hunk 1]
```diff
@@ -2139,8 +2139,9 @@ namespace meta
             struct find_if_<list<List...>, Fun,
                             void_<integer_sequence<bool, bool(invoke<Fun, List>::type::value)...>>>
             {
-#if defined(__clang__) && __clang_major__ < 6
+#if (defined(__clang__) && __clang_major__ < 6) || defined(__apple_build_version__)
```
Comment (CaseyCarter) [inline include/meta/meta.hpp]: There are roughly half a dozen occurrences of `// Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385` in here which need to be fixed similarly.

File: include/meta/meta.hpp [hunk 2]
```diff
@@ -2139,8 +2139,9 @@ namespace meta
...
                 // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
+                // Track Apples version here: https://en.wikipedia.org/wiki/Xcode#Toolchain_Versions
```
Comment (CaseyCarter) [inline include/meta/meta.hpp]: "Apples" should be "Apple's"

File: include/meta/meta.hpp (hunk 1 above)
Comment (maikel) [reply include/meta/meta.hpp]: Right, I haven't looked for more occurrences. My code base used `meta::find_if` directly at several places. I've searched this file for the string '28385' and fixed it at every place which I've found that way.

    grep -Rn '28385' .
    ./meta/meta.hpp:1994:                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
    ./meta/meta.hpp:2052:                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
    ./meta/meta.hpp:2145:                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
    ./meta/meta.hpp:2206:                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
    ./meta/meta.hpp:2334:                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
    ./meta/meta.hpp:2379:                // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385

File: include/meta/meta.hpp [hunk 3]
```diff
@@ -1990,8 +1990,9 @@ namespace meta
             template <typename... T, typename V>
             struct find_index_<list<T...>, V>
             {
-#if defined(__clang__) && __clang_major__ < 6
+#if (defined(__clang__) && __clang_major__ < 6) || defined(__apple_build_version__)
                 // Explicitly specify extent to avoid https://llvm.org/bugs/show_bug.cgi?id=28385
+                // Track Apple's version here: https://en.wikipedia.org/wiki/Xcode#Toolchain_Versions
```
Comment (CaseyCarter) [inline include/meta/meta.hpp]: Having now actually looked at this page, there's no useful information there: I don't think we need these Wikipedia links. We like having links to trackable bugs for workarounds like this so the workarounds can be scoped to the buggy compiler versions and eventually dropped along with support for said buggy compiler versions. I vaguely recall hearing someone mention that Apple doesn't have a publicly accessible bug tracking database so there may be no way for us to get such a link in this case. If you happen to know that I'm mistaken, then please speak up, but otherwise we should simply remove the wikipedia links and hope that someone some day will tell us this bug has been fixed in some Apple clang version.

Comment (maikel) [reply include/meta/meta.hpp]: Alright, I somehow assumed the link provided a mapping of Apple's LLVM version to the official one. But I was apparently mistaken as it doesn't include newer versions.
