### PR TITLE
Defer Invokable test in ranges::action

### LINKED ISSUE #632: action::stable_sort of vector broken on Clang 3.8.1 since ~last Xmas
This code used to compile and run under Clang 3.8.1:

~~~~~.cpp
#include <range/v3/all.hpp>

#include <iostream>
#include <vector>

int main() {
	const std::vector<double> scores = { 3.0, 1.0, 2.0 };
	std::vector<int> indices = { 0, 1, 2 };

	indices |= ranges::action::stable_sort(
		ranges::less{},
		[&] (const int &x) { return scores[ x ]; }
	);

	std::cerr << ( indices | ranges::view::all ) << "\n";
}
~~~~~

...but since 61917222962c9cb5e1056bdc175cf31ab1894f1c, it gives errors:

~~~~~
In file included from range-v3.stable-sort-prob.cpp:1:
In file included from range-v3/include/range/v3/all.hpp:19:
In file included from range-v3/include/range/v3/action.hpp:30:
range-v3/include/range/v3/action/stable_sort.hpp:73:21: error: static_assert failed "The object on which action::stable_sort operates must be a model of the ForwardRange concept."
                    CONCEPT_ASSERT_MSG(ForwardRange<Rng>(),
                    ^                  ~~~~~~~~~~~~~~~~~~~
range-v3/include/range/v3/utility/concepts.hpp:812:28: note: expanded from macro 'CONCEPT_ASSERT_MSG'
#define CONCEPT_ASSERT_MSG static_assert
                           ^
range-v3/include/range/v3/utility/invoke.hpp:124:17: note: in instantiation of function template specialization 'ranges::v3::action::stable_sort_fn::operator()<ranges::v3::less &, (lambda at range-v3.stable-sort-prob.cpp:12:3), ranges::v3::ident, 42, 0>' requested here
                detail::forward<F>(fn)(detail::forward<Args>(args)...)
                ^
In file included from range-v3.stable-sort-prob.cpp:1:
In file included from range-v3/include/range/v3/all.hpp:17:
In file included from range-v3/include/range/v3/core.hpp:18:
In file included from range-v3/include/range/v3/distance.hpp:22:
In file included from range-v3/include/range/v3/range_traits.hpp:24:
range-v3/include/range/v3/range_concepts.hpp:64:45: error: no matching function for call to object of type 'const ranges::v3::adl_begin_end_detail::begin_fn'
                using iterator_t = decltype(begin(std::declval<T&>()));
                                            ^~~~~
range-v3/include/range/v3/range_traits.hpp:35:9: note: in instantiation of template type alias 'iterator_t' requested here
        using range_iterator_t = concepts::Range::iterator_t<Rng>;
        ^
range-v3/include/range/v3/action/stable_sort.hpp:76:31: note: in instantiation of template type alias 'range_iterator_t' requested here
                    using I = range_iterator_t<Rng>;
                              ^
range-v3/include/range/v3/utility/invoke.hpp:124:17: note: in instantiation of function template specialization 'ranges::v3::action::stable_sort_fn::operator()<ranges::v3::less &, (lambda at range-v3.stable-sort-prob.cpp:12:3), ranges::v3::ident, 42, 0>' requested here
                detail::forward<F>(fn)(detail::forward<Args>(args)...)
                ^
range-v3/include/range/v3/begin_end.hpp:105:32: note: candidate template ignored: substitution failure [with Rng = ranges::v3::less &]: no matching function for call to 'impl'
                constexpr auto operator()(Rng && rng) const
                               ^
In file included from range-v3.stable-sort-prob.cpp:1:
In file included from range-v3/include/range/v3/all.hpp:19:
In file included from range-v3/include/range/v3/action.hpp:30:
range-v3/include/range/v3/action/stable_sort.hpp:77:21: error: static_assert failed "The projection function must accept objects of the iterator's value type, reference type, and common reference type."
                    CONCEPT_ASSERT_MSG(IndirectInvocable<P, I>(),
                    ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~
range-v3/include/range/v3/utility/concepts.hpp:812:28: note: expanded from macro 'CONCEPT_ASSERT_MSG'
#define CONCEPT_ASSERT_MSG static_assert
                           ^
range-v3/include/range/v3/utility/invoke.hpp:124:17: note: in instantiation of function template specialization 'ranges::v3::action::stable_sort_fn::operator()<ranges::v3::less &, (lambda at range-v3.stable-sort-prob.cpp:12:3), ranges::v3::ident, 42, 0>' requested here
                detail::forward<F>(fn)(detail::forward<Args>(args)...)
                ^
In file included from range-v3.stable-sort-prob.cpp:1:
In file included from range-v3/include/range/v3/all.hpp:17:
In file included from range-v3/include/range/v3/core.hpp:17:
In file included from range-v3/include/range/v3/begin_end.hpp:21:
In file included from range-v3/include/range/v3/range_fwd.hpp:20:
range-v3/include/meta/meta.hpp:140:9: error: no type named 'type' in 'meta::v1::detail::_if_<meta::v1::list<std::__1::integral_constant<bool, false>, ranges::v3::detail::projected_<int, ranges::v3::ident> >, bool>'
        using _t = typename T::type;
        ^~~~~
range-v3/include/meta/meta.hpp:1110:9: note: in instantiation of template type alias '_t' requested here
        using if_c = _t<detail::_if_<list<bool_<If>, Args...>>>;
        ^
range-v3/include/range/v3/utility/iterator_concepts.hpp:568:9: note: in instantiation of template type alias 'if_c' requested here
        using projected = meta::if_c<IndirectInvocable<Proj, I>::value, detail::projected_<I, Proj>>;
        ^
range-v3/include/range/v3/action/stable_sort.hpp:80:60: note: in instantiation of template type alias 'projected' requested here
                    CONCEPT_ASSERT_MSG(IndirectRelation<C, projected<I, P>>(),
                                                           ^
range-v3/include/range/v3/utility/invoke.hpp:124:17: note: in instantiation of function template specialization 'ranges::v3::action::stable_sort_fn::operator()<ranges::v3::less &, (lambda at range-v3.stable-sort-prob.cpp:12:3), ranges::v3::ident, 42, 0>' requested here
                detail::forward<F>(fn)(detail::forward<Args>(args)...)
                ^
4 errors generated.
~~~~~

From what I can see on Wandbox, the problem disappears for Clang &ge; 4.0.

### PR DESCRIPTION
**Pull request by ericniebler**
Also:
- fix up many action concept tests
- add tests for `action::stable_sort` and `action::view`

fixes #632

### CODE REVIEW

**Comment by tonyelewis** [comment]
Thanks very much for looking into this so quickly.

I'm finding that this PR fixes my Clang but breaks my GCC 6.2.0 (coloured diagnostics in attached file) :

~~~~~
In file included from range-v3/include/range/v3/range_fwd.hpp:20:0,
                 from range-v3/include/range/v3/begin_end.hpp:22,
                 from range-v3/include/range/v3/core.hpp:17,
                 from range-v3/include/range/v3/all.hpp:17,
                 from range-v3.issue-632.cpp:1:
range-v3/include/meta/meta.hpp: In instantiation of ‘struct meta::v1::detail::_and_<meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, const volatile ranges::v3::less&, const volatile main()::<lambda(const int&)>&>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> > >’:
range-v3/include/meta/meta.hpp:1137:20:   required from ‘struct meta::v1::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::ForwardRange, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> >, meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, const volatile ranges::v3::less&, const volatile main()::<lambda(const int&)>&>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> > >’
range-v3/include/range/v3/action/sort.hpp:65:21:   required by substitution of ‘template<class Rng, class C, class P, int _concept_requires_65, typename std::enable_if<((_concept_requires_65 == 43) || (! typename meta::v1::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::ForwardRange, T>, meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, C, P>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, Rng> >::type())), int>::type <anonymous> > void ranges::v3::action::stable_sort_fn::operator()(Rng&&, C&&, P&&) const [with Rng = ranges::v3::reference_wrapper<std::vector<int>, false>; C = const volatile ranges::v3::less&; P = const volatile main()::<lambda(const int&)>&; int _concept_requires_65 = 42; typename std::enable_if<((_concept_requires_65 == 43) || (! typename meta::v1::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::ForwardRange, T>, meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, C, P>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, Rng> >::type())), int>::type <anonymous> = <missing>]’
/usr/include/c++/6/functional:1036:64:   required by substitution of ‘template<class ... _Args, class _Result> _Result std::_Bind<_Functor(_Bound_args ...)>::operator()(_Args&& ...) const volatile [with _Args = {ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>}; _Result = <missing>]’
range-v3/include/range/v3/utility/invoke.hpp:125:13:   required by substitution of ‘template<class F, class ... Args, typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> > constexpr decltype (static_cast<F&&>(fn)(static_cast<Args&>(ranges::v3::invoke_fn::operator()::args) ...)) ranges::v3::invoke_fn::operator()(F&&, Args&& ...) const [with F = std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)>&; Args = {ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>}; typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> = 0]’
range-v3/include/range/v3/utility/invoke.hpp:171:28:   required by substitution of ‘template<class T> T ranges::v3::detail::gcc_bugs_bugs_bugs(T) [with T = <missing>]’
range-v3/include/range/v3/utility/concepts.hpp:111:55:   [ skipping 6 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
range-v3/include/range/v3/utility/invoke.hpp:125:13:   required by substitution of ‘template<class F, class ... Args, typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> > constexpr decltype (static_cast<F&&>(fn)(static_cast<Args&>(ranges::v3::invoke_fn::operator()::args) ...)) ranges::v3::invoke_fn::operator()(F&&, Args&& ...) const [with F = ranges::v3::bitwise_or; Args = {ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>, ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >&}; typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> = 0]’
range-v3/include/range/v3/utility/invoke.hpp:171:28:   required by substitution of ‘template<class T> T ranges::v3::detail::gcc_bugs_bugs_bugs(T) [with T = <missing>]’
range-v3/include/range/v3/utility/concepts.hpp:111:55:   required by substitution of ‘template<class ... Ts, class Concept, class> meta::v1::apply<meta::v1::quote<meta::v1::lazy::strict_and>, typename meta::v1::detail::transform_<meta::v1::list<typename ranges::v3::detail::base_concepts_of<Concept, void>::type, meta::v1::bind_back<meta::v1::quote<ranges::v3::concepts::models>, Ts ...> >, void>::type> ranges::v3::detail::models_(Concept*) [with Ts = {ranges::v3::bitwise_or, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>, ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >&}; Concept = ranges::v3::concepts::Invocable; <template-parameter-1-3> = <missing>]’
range-v3/include/range/v3/utility/concepts.hpp:187:69:   required from ‘struct ranges::v3::concepts::models<ranges::v3::concepts::Invocable, ranges::v3::bitwise_or, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>, ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >&>’
range-v3/include/range/v3/action/action.hpp:132:17:   required by substitution of ‘template<class Rng, class Action, int _concept_requires_135, typename std::enable_if<((_concept_requires_135 == 43) || (((ranges::v3::is_pipeable<Pipe>() && ranges::v3::concepts::models<ranges::v3::concepts::Range, T&>()) && ranges::v3::concepts::models<ranges::v3::concepts::Invocable, ranges::v3::bitwise_or, decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), Action&>()) && typename ranges::v3::concepts::Same::same<decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), typename ranges::v3::result_of<ranges::v3::bitwise_or(decltype (ranges::v3::{anonymous}::ref(declval<Rng&>()))&&, Action&), void>::type>::type())), int>::type <anonymous> > Rng& ranges::v3::action::operator|=(Rng&, Action&&) [with Rng = std::vector<int>; Action = ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >; int _concept_requires_135 = 42; typename std::enable_if<((_concept_requires_135 == 43) || (((ranges::v3::is_pipeable<Pipe>() && ranges::v3::concepts::models<ranges::v3::concepts::Range, T&>()) && ranges::v3::concepts::models<ranges::v3::concepts::Invocable, ranges::v3::bitwise_or, decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), Action&>()) && typename ranges::v3::concepts::Same::same<decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), typename ranges::v3::result_of<ranges::v3::bitwise_or(decltype (ranges::v3::{anonymous}::ref(declval<Rng&>()))&&, Action&), void>::type>::type())), int>::type <anonymous> = <missing>]’
range-v3.issue-632.cpp:13:2:   required from here
range-v3/include/meta/meta.hpp:1138:24: error: no type named ‘type’ in ‘struct meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, const volatile ranges::v3::less&, const volatile main()::<lambda(const int&)>&>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> >’
                 : if_c<!Bool_::type::value, std::false_type, _and_<Bools...>>
                        ^~~~~~
range-v3/include/meta/meta.hpp: In instantiation of ‘struct meta::v1::detail::_and_<meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, volatile ranges::v3::less&, volatile main()::<lambda(const int&)>&>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> > >’:
range-v3/include/meta/meta.hpp:1137:20:   required from ‘struct meta::v1::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::ForwardRange, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> >, meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, volatile ranges::v3::less&, volatile main()::<lambda(const int&)>&>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> > >’
range-v3/include/range/v3/action/sort.hpp:65:21:   required by substitution of ‘template<class Rng, class C, class P, int _concept_requires_65, typename std::enable_if<((_concept_requires_65 == 43) || (! typename meta::v1::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::ForwardRange, T>, meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, C, P>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, Rng> >::type())), int>::type <anonymous> > void ranges::v3::action::stable_sort_fn::operator()(Rng&&, C&&, P&&) const [with Rng = ranges::v3::reference_wrapper<std::vector<int>, false>; C = volatile ranges::v3::less&; P = volatile main()::<lambda(const int&)>&; int _concept_requires_65 = 42; typename std::enable_if<((_concept_requires_65 == 43) || (! typename meta::v1::detail::_and_<ranges::v3::concepts::models<ranges::v3::concepts::ForwardRange, T>, meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, C, P>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, Rng> >::type())), int>::type <anonymous> = <missing>]’
/usr/include/c++/6/functional:1022:70:   required by substitution of ‘template<class ... _Args, class _Result> _Result std::_Bind<_Functor(_Bound_args ...)>::operator()(_Args&& ...) volatile [with _Args = {ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>}; _Result = <missing>]’
range-v3/include/range/v3/utility/invoke.hpp:125:13:   required by substitution of ‘template<class F, class ... Args, typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> > constexpr decltype (static_cast<F&&>(fn)(static_cast<Args&>(ranges::v3::invoke_fn::operator()::args) ...)) ranges::v3::invoke_fn::operator()(F&&, Args&& ...) const [with F = std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)>&; Args = {ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>}; typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> = 0]’
range-v3/include/range/v3/utility/invoke.hpp:171:28:   required by substitution of ‘template<class T> T ranges::v3::detail::gcc_bugs_bugs_bugs(T) [with T = <missing>]’
range-v3/include/range/v3/utility/concepts.hpp:111:55:   [ skipping 6 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
range-v3/include/range/v3/utility/invoke.hpp:125:13:   required by substitution of ‘template<class F, class ... Args, typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> > constexpr decltype (static_cast<F&&>(fn)(static_cast<Args&>(ranges::v3::invoke_fn::operator()::args) ...)) ranges::v3::invoke_fn::operator()(F&&, Args&& ...) const [with F = ranges::v3::bitwise_or; Args = {ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>, ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >&}; typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, (! std::is_member_pointer<typename std::remove_cv<typename std::remove_reference<_From>::type>::type>::value)>, int>, std::integral_constant<bool, true> >::type <anonymous> = 0]’
range-v3/include/range/v3/utility/invoke.hpp:171:28:   required by substitution of ‘template<class T> T ranges::v3::detail::gcc_bugs_bugs_bugs(T) [with T = <missing>]’
range-v3/include/range/v3/utility/concepts.hpp:111:55:   required by substitution of ‘template<class ... Ts, class Concept, class> meta::v1::apply<meta::v1::quote<meta::v1::lazy::strict_and>, typename meta::v1::detail::transform_<meta::v1::list<typename ranges::v3::detail::base_concepts_of<Concept, void>::type, meta::v1::bind_back<meta::v1::quote<ranges::v3::concepts::models>, Ts ...> >, void>::type> ranges::v3::detail::models_(Concept*) [with Ts = {ranges::v3::bitwise_or, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>, ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >&}; Concept = ranges::v3::concepts::Invocable; <template-parameter-1-3> = <missing>]’
range-v3/include/range/v3/utility/concepts.hpp:187:69:   required from ‘struct ranges::v3::concepts::models<ranges::v3::concepts::Invocable, ranges::v3::bitwise_or, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false>, ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >&>’
range-v3/include/range/v3/action/action.hpp:132:17:   required by substitution of ‘template<class Rng, class Action, int _concept_requires_135, typename std::enable_if<((_concept_requires_135 == 43) || (((ranges::v3::is_pipeable<Pipe>() && ranges::v3::concepts::models<ranges::v3::concepts::Range, T&>()) && ranges::v3::concepts::models<ranges::v3::concepts::Invocable, ranges::v3::bitwise_or, decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), Action&>()) && typename ranges::v3::concepts::Same::same<decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), typename ranges::v3::result_of<ranges::v3::bitwise_or(decltype (ranges::v3::{anonymous}::ref(declval<Rng&>()))&&, Action&), void>::type>::type())), int>::type <anonymous> > Rng& ranges::v3::action::operator|=(Rng&, Action&&) [with Rng = std::vector<int>; Action = ranges::v3::action::action<std::_Bind<ranges::v3::action::stable_sort_fn(std::_Placeholder<1>, ranges::v3::less, main()::<lambda(const int&)>)> >; int _concept_requires_135 = 42; typename std::enable_if<((_concept_requires_135 == 43) || (((ranges::v3::is_pipeable<Pipe>() && ranges::v3::concepts::models<ranges::v3::concepts::Range, T&>()) && ranges::v3::concepts::models<ranges::v3::concepts::Invocable, ranges::v3::bitwise_or, decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), Action&>()) && typename ranges::v3::concepts::Same::same<decltype (ranges::v3::{anonymous}::ref(declval<Rng&>())), typename ranges::v3::result_of<ranges::v3::bitwise_or(decltype (ranges::v3::{anonymous}::ref(declval<Rng&>()))&&, Action&), void>::type>::type())), int>::type <anonymous> = <missing>]’
range-v3.issue-632.cpp:13:2:   required from here
range-v3/include/meta/meta.hpp:1138:24: error: no type named ‘type’ in ‘struct meta::v1::defer<meta::v1::invoke, meta::v1::compose<meta::v1::bind_back<meta::v1::quote<ranges::v3::Sortable>, volatile ranges::v3::less&, volatile main()::<lambda(const int&)>&>, meta::v1::quote<ranges::v3::concepts::Range::iterator_t> >, ranges::v3::reference_wrapper<std::vector<int, std::allocator<int> >, false> >’
~~~~~

[475a1e0.gcc_colour.txt](https://github.com/ericniebler/range-v3/files/906332/475a1e0.gcc_colour.txt)

File: include/range/v3/action/stable_sort.hpp [hunk 1]
```diff
@@ -43,19 +43,14 @@ namespace ranges
...
-
                 template<typename Rng, typename C = ordered_less, typename P = ident>
-                using Concept = concepts::models<ConceptImpl, Rng, C, P>;
+                using Concept = meta::and_<
+                    ForwardRange<Rng>,
+                    meta::lazy::invoke<
+                        meta::compose<
+                            meta::bind_back<meta::quote<Sortable>, C, P>,
+                            meta::quote<iterator_t>>,
+                        Rng>>;
```
Comment (CaseyCarter) [inline include/range/v3/action/stable_sort.hpp]: This constraint is identical to that in action/sort.hpp. Should we factor it out into a `SortableRange` concept?

File: test/action/join.cpp [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+#include <vector>
+#include <range/v3/core.hpp>
+#include <range/v3/action/join.hpp>
+#include <range/v3/algorithm/move.hpp>
+#include <range/v3/algorithm/equal.hpp>
+#include <range/v3/view/transform.hpp>
+#include "../simple_test.hpp"
+#include "../test_utils.hpp"
+
+template<class> struct undef;
```
Comment (CaseyCarter) [inline test/action/join.cpp]: You've left your type printer debugging tool in the code.

Comment (CaseyCarter) [inline test/action/join.cpp]: With a more descriptive name - I always call it `show_type` and make it variadic - it would be a good idea to put an intentionally undefined template in e.g. `test_utils`. It would not suck to never have to type this line of code again.

File: test/action/join.cpp [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+
+int main()
+{
+    using namespace ranges;
+
+    std::vector<std::string> v {"hello"," ","world"};
```
Comment (CaseyCarter) [inline test/action/join.cpp]: `#include <string>`

**Comment by ericniebler** [comment]
I borrowed some ideas from @odinthenerd to make `meta::and_` and `meta::or_` SFINAE-friendly *and* compile faster. Let's see what Travis makes of this.

File: test/action/join.cpp (hunk 2 above)
Comment (gnzlbg) [inline test/action/join.cpp]: I always call it `dump`, would be nice to have this in `test_utils`.

**Comment by ericniebler** [comment]
I'm really struggling getting this to compile on Clang 3.6 and GCC 4.8. If anybody thinks they can do it I would gladly accept help.

**Comment by tonyelewis** [comment]
FWIW, I can confirm that the PR has now fixed #632 for me on Clang 3.8.1 and GCC 6.2.0.

I'd be happy to help but it's very doubtful that I'd make more progress than you.

**Comment by tonyelewis** [comment]
FYI: at da45d36cacf47ac9b3bba0e1e66cb37fc1586f48, my original #632 code is still working under both Clang 3.8.1 and GCC 6.2.0.

**Comment by ericniebler** [comment]
Attn @CaseyCarter : I have rebased this branch. Be careful.

**Comment by tonyelewis** [comment]
FYI: at the rebased tip d37200838eaba26547d30cb628137644621c515f, my original #632 code is still working under both Clang 3.8.1 and GCC 6.2.0.

**Comment by CaseyCarter** [comment]
This has been a ridiculously complicated bug fix. We really should ban @tonyelewis ;)

**Comment by ericniebler** [comment]
Eagerly anticipating a time when I can drop gcc-4.x support.

**Comment by CaseyCarter** [comment]
> I'm really struggling getting this to compile on Clang 3.6 and GCC 4.8

I really hope this "4.8" is a typo. 141 of 203 tests ICE on utility/concepts.hpp line 111 for me compiling with 4.8.

**Comment by ericniebler** [comment]
Yes, I meant gcc-4.9. I dropped gcc-4.8 with the 0.2.0 release, and there's no going back now.

**Comment by ericniebler** [comment]
FINALLY.

**Comment by tonyelewis** [comment]
Apologies for being a trouble-causer. ;)

**Comment by tonyelewis** [comment]
I like the implementation of `std::is_function`. It took me a few moments to decipher it because I'm not massively familiar with a few of the techniques :confused:. Is the `priority_tag` approach novel?

**Comment by CaseyCarter** [comment]
>  Is the `priority_tag` approach novel?

 I picked up the technique on Stackoverflow years ago; I've seen it attributed to Xeo. In addition to being more extensible, I think it expresses intent far more clearly than ad-hoc `int` vs. `long` vs. `nullptr_t` vs. `...` overloading.
