### PR TITLE
span::subspan<N, -1>() is equivalent to subspan<N>()

### LINKED ISSUE #799: span::subspan<0, -1>() is broken
Per [P0122](https://wg21.link/p0122) `subspan<0, dynamic_extent>()` should be equivalent to `subspan<0>()` instead of being ill-formed.

### PR DESCRIPTION
**Pull request by CaseyCarter**
Fixes #799.

### CODE REVIEW

File: include/range/v3/span.hpp [hunk 1]
```diff
@@ -97,6 +97,10 @@ namespace ranges
             private:
                 span_index_t size_ = 0;
             };
+
+            template<span_index_t Extent, span_index_t Offset, span_index_t Count>
+            using subspan_extent = std::integral_constant<span_index_t,
+                Count == dynamic_extent && Extent != dynamic_extent ? Extent - Offset : Count>;
```
Comment (ericniebler) [inline include/range/v3/span.hpp]: Why isn't this just a `constexpr` function?

Comment (CaseyCarter) [reply include/range/v3/span.hpp]: For absolutely no good reason.
