### PR TITLE
Fully support const & mutable underlying views in view::bounded.

### LINKED ISSUE #504: Compile failure on operator<< of repeat_n( 0, 10 ) | bounded
The following fails to compile under both Clang and GCC:

~~~~~.cpp
#include <range/v3/all.hpp>

#include <iostream>

int main() {
	std::cerr << ( ranges::view::repeat_n( 0, 10 ) | ranges::view::bounded ) << "\n";
}
~~~~~

Apologies if this is erroneous usage. Start of GCC errors:

~~~~~
In file included from i/range/v3/view.hpp:24:0,
                 from i/range/v3/all.hpp:21,
                 from rangev3_repeat_n_bounded.cpp:1:
i/range/v3/view/bounded.hpp: In instantiation of ‘ranges::v3::bounded_view<Rng>::iterator ranges::v3::bounded_view<Rng>::end() const [with int _concept_requires_85 = 42; typename std::enable_if<((_concept_requires_80 == 43) || ranges::v3::concepts::models<ranges::v3::concepts::View, const Rng>()), int>::type <anonymous> = 0; Rng = ranges::v3::repeat_n_view<int>; ranges::v3::bounded_view<Rng>::iterator = ranges::v3::basic_iterator<ranges::v3::repeat_n_view<int>::cursor, ranges::v3::default_end_cursor>]’:
i/range/v3/begin_end.hpp:129:36:   required from ‘static constexpr decltype (rng.end()) ranges::v3::adl_begin_end_detail::end_fn::impl(Rng&&, int) [with Rng = const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> >&; typename meta::v1::detail::_if_<meta::v1::list<std::integral_constant<bool, std::is_lvalue_reference< <template-parameter-1-1> >::value>, int>, std::integral_constant<bool, true> >::type <anonymous> = 0; decltype (rng.end()) = ranges::v3::basic_iterator<ranges::v3::repeat_n_view<int>::cursor, ranges::v3::default_end_cursor>]’
i/range/v3/begin_end.hpp:133:32:   required from ‘constexpr ranges::v3::detail::decay_t<decltype (ranges::v3::adl_begin_end_detail::end_fn::impl(static_cast<Rng&&>(rng), 0))> ranges::v3::adl_begin_end_detail::end_fn::operator()(Rng&&) const [with Rng = const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> >&; ranges::v3::detail::decay_t<decltype (ranges::v3::adl_begin_end_detail::end_fn::impl(static_cast<Rng&&>(rng), 0))> = ranges::v3::basic_iterator<ranges::v3::repeat_n_view<int>::cursor, ranges::v3::default_end_cursor>]’
i/range/v3/range_concepts.hpp:74:57:   required by substitution of ‘template<class T> decltype (ranges::v3::detail::valid_expr(model_of<ranges::v3::concepts::Sentinel>(ranges::v3::{anonymous}::end(t), ranges::v3::{anonymous}::begin(t)))) ranges::v3::concepts::Range::requires_(T&&) [with T = const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> >]’
i/range/v3/utility/concepts.hpp:113:17:   required by substitution of ‘template<class ... Ts, class Concept, class> meta::v1::apply<meta::v1::quote<meta::v1::lazy::strict_and>, typename meta::v1::detail::transform_<meta::v1::list<typename ranges::v3::detail::base_concepts_of<Concept, void>::type, meta::v1::bind_back<meta::v1::quote<ranges::v3::concepts::models>, Ts ...> >, void>::type> ranges::v3::detail::models_(Concept*) [with Ts = {const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> >}; Concept = ranges::v3::concepts::Range; <template-parameter-1-3> = void]’
i/range/v3/utility/concepts.hpp:212:69:   required from ‘struct ranges::v3::concepts::models<ranges::v3::concepts::Range, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >’
i/meta/meta.hpp:1186:56:   required by substitution of ‘template<class ... Bools> using strict_and = meta::v1::and_c<Bools::type::value ...> [with Bools = {ranges::v3::concepts::models<ranges::v3::concepts::Range, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >}]’
i/meta/meta.hpp:646:21:   required by substitution of ‘template<template<class ...> class C, class ... Ts, class> meta::v1::detail::defer_if_::result<C, Ts ...> meta::v1::detail::defer_if_::try_() [with C = meta::v1::strict_and; Ts = {ranges::v3::concepts::models<ranges::v3::concepts::Range, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >}; <template-parameter-1-3> = std::is_same<meta::v1::integer_sequence<bool, true>, meta::v1::integer_sequence<bool, true> >]’
i/meta/meta.hpp:667:66:   required by substitution of ‘template<template<class ...> class C, class ... Ts> using defer_ = decltype (meta::v1::detail::defer_if_{}.try_<template<class ...> class C, Ts ...>()) [with C = meta::v1::strict_and; Ts = {ranges::v3::concepts::models<ranges::v3::concepts::Range, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >}]’
i/meta/meta.hpp:712:16:   required from ‘struct meta::v1::defer<meta::v1::strict_and, ranges::v3::concepts::models<ranges::v3::concepts::Range, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > > >’
i/range/v3/utility/concepts.hpp:211:20:   required from ‘struct ranges::v3::concepts::models<ranges::v3::concepts::View, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >’
i/meta/meta.hpp:1186:56:   required by substitution of ‘template<class ... Bools> using strict_and = meta::v1::and_c<Bools::type::value ...> [with Bools = {ranges::v3::concepts::models<ranges::v3::concepts::View, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >, ranges::v3::concepts::models<ranges::v3::concepts::InputRange, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >}]’
i/meta/meta.hpp:646:21:   required by substitution of ‘template<template<class ...> class C, class ... Ts, class> meta::v1::detail::defer_if_::result<C, Ts ...> meta::v1::detail::defer_if_::try_() [with C = meta::v1::strict_and; Ts = {ranges::v3::concepts::models<ranges::v3::concepts::View, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >, ranges::v3::concepts::models<ranges::v3::concepts::InputRange, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >}; <template-parameter-1-3> = std::is_same<meta::v1::integer_sequence<bool, true, true>, meta::v1::integer_sequence<bool, true, true> >]’
i/meta/meta.hpp:667:66:   required by substitution of ‘template<template<class ...> class C, class ... Ts> using defer_ = decltype (meta::v1::detail::defer_if_{}.try_<template<class ...> class C, Ts ...>()) [with C = meta::v1::strict_and; Ts = {ranges::v3::concepts::models<ranges::v3::concepts::View, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >, ranges::v3::concepts::models<ranges::v3::concepts::InputRange, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >}]’
i/meta/meta.hpp:712:16:   required from ‘struct meta::v1::defer<meta::v1::strict_and, ranges::v3::concepts::models<ranges::v3::concepts::View, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >, ranges::v3::concepts::models<ranges::v3::concepts::InputRange, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > > >’
i/range/v3/utility/concepts.hpp:211:20:   required from ‘struct ranges::v3::concepts::models<ranges::v3::concepts::InputView, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> > >’
i/range/v3/view_interface.hpp:276:39:   required by substitution of ‘template<bool B, class Stream, class D, int _concept_requires_276, typename std::enable_if<((_concept_requires_276 == 43) || ranges::v3::concepts::models<ranges::v3::concepts::InputView, const D>()), int>::type <anonymous> > Stream& ranges::v3::operator<<(Stream&, const ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> >&) [with bool B = true; Stream = std::basic_ostream<char>; D = ranges::v3::bounded_view<ranges::v3::repeat_n_view<int> >; int _concept_requires_276 = 42; typename std::enable_if<((_concept_requires_276 == 43) || ranges::v3::concepts::models<ranges::v3::concepts::InputView, const D>()), int>::type <anonymous> = 0]’
rangev3_repeat_n_bounded.cpp:6:73:   required from here
i/range/v3/view/bounded.hpp:88:50: error: no matching function for call to ‘ranges::v3::basic_iterator<ranges::v3::repeat_n_view<int>::cursor, ranges::v3::default_end_cursor>::basic_iterator(<brace-enclosed initializer list>)’
                 return iterator{ranges::end(rng_)};
                                                  ^
~~~~~

Full Clang/GCC errors, with/without colouring :

[gcc_errors.plain.txt](https://github.com/ericniebler/range-v3/files/594082/gcc_errors.plain.txt)
[gcc_errors.colour.txt](https://github.com/ericniebler/range-v3/files/594080/gcc_errors.colour.txt)
[clang_errors.plain.txt](https://github.com/ericniebler/range-v3/files/594083/clang_errors.plain.txt)
[clang_errors.colour.txt](https://github.com/ericniebler/range-v3/files/594081/clang_errors.colour.txt)

Many thanks for your continuing work on this wonderful library.

### PR DESCRIPTION
**Pull request by CaseyCarter**
Err, fixes #504.

### CODE REVIEW

File: include/range/v3/view/bounded.hpp [hunk 1]
```diff
@@ -41,65 +41,82 @@ namespace ranges
...
-                meta::strict_and<RandomAccessRange<Rng>, SizedRange<Rng>>;
-            using base_iterator_t = range_iterator_t<Rng>;
-            using base_sentinel_t = range_sentinel_t<Rng>;
+                meta::strict_and<RandomAccessRange<R>, SizedRange<R>>;
+            template<typename R>
+            using bounded_iterator_t = meta::if_<RA_and_Sized<R>,
+                range_iterator_t<R>,
+                common_iterator<range_iterator_t<R>, range_sentinel_t<R>>>;
+            template<typename R>
+            using bounded_iterator = meta::defer<bounded_iterator_t, R>;
```
Comment (CaseyCarter) [inline include/range/v3/view/bounded.hpp]: This alias is dead, moron. Remove it.

Comment (CaseyCarter) [inline include/range/v3/view/bounded.hpp]: ...and move these non-dependent aliases out into the detail namespace while you're at it.

**Comment by tonyelewis** [comment]
Thanks very much for this. Much appreciated.

When combined with P-R #503, this makes the following work:

~~~~~.cpp
boost::algorithm::join(
  ranges::view::repeat_n( std::string{ "lonely roads" }, 4 ) | ranges::view::bounded,
  "\n"
)
~~~~~

(where the `bounded` is necessary to make the sentinel-using `repeat_n` usable by Boost)

Bonzer!
