### PR TITLE
Make any_view<Ref> = Rng work ...

### LINKED ISSUE #444: any_view fails on a simple view_facade-based range
Here's a simple range that yields odd numbers, and I'm trying to type-erase it via `any_view`:

```cpp
#include <range/v3/all.hpp>

template<typename T, CONCEPT_REQUIRES_(ranges::Integral<T>())>
class odd : public ranges::view_facade<odd<T>> {
    friend ranges::range_access;
    T max_, curr_;

    const T& get() const { return curr_; }
    bool done() const { return curr_ >= max_; }
    void next() { curr_ += 2; }

public:
    odd() = default;
    odd(T min, T max) : max_(max), curr_(min % 2 ? min : min + 1) { }
};

int main() {
    ranges::any_view<int> r = odd<int>(10, 21);
}
```

While the range itself obviously works as intended, the conversion to `any_view` fails in a weird way (this is on gcc 5.3.1, c++14).

I'm not quite sure about all the details but it looks like it fails to initialize the unique_ptr containing `any_view_interface` impl for some reason.

Wonder if I'm doing something wrong or something's wrong with `any_view`?

```sh
In file included from range-v3/include/range/v3/view.hpp:23:0,
                 from range-v3/include/range/v3/all.hpp:21,
                 from range.cpp:5:
range-v3/include/range/v3/view/any_view.hpp: In instantiation of ‘ranges::v3::any_view<Ref, Cat>::any_view(Rng&&, std::true_type) [with Rng = odd<int>; Ref = int; ranges::v3::category Cat = (ranges::v3::category)0; std::true_type = std::integral_constant<bool, true>]’:
range-v3/include/range/v3/view/any_view.hpp:381:78:   required from ‘ranges::v3::any_view<Ref, Cat>::any_view(Rng&&) [with Rng = odd<int>; int _concept_requires_376 = 42; typename std::enable_if<((_concept_requires_376 == 43) || (! typename ranges::v3::concepts::Same::same<typename std::decay<_Tp>::type, ranges::v3::any_view<Ref, Cat> >::type())), int>::type <anonymous> = 0; int _concept_requires_378 = 42; typename std::enable_if<((_concept_requires_222 == 43) || (ranges::v3::concepts::models<ranges::v3::concepts::InputRange, R>() && ranges::v3::concepts::models<ranges::v3::concepts::ConvertibleTo, decltype (* declval<decltype (ranges::v3::{anonymous}::begin(declval<D&>()))&>()), Ref>())), int>::type <anonymous> = 0; Ref = int; ranges::v3::category Cat = (ranges::v3::category)0]’
range.cpp:47:49:   required from here
range-v3/include/range/v3/view/any_view.hpp:364:55: error: no matching function for call to ‘std::unique_ptr<ranges::v3::detail::any_view_interface<int, (ranges::v3::category)0>, std::default_delete<ranges::v3::detail::any_view_interface<int, (ranges::v3::category)0> > >::unique_ptr(<brace-enclosed initializer list>)’
                     view::all(std::forward<Rng>(rng))}}
                                                       ^
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.2.1/memory:81:0,
                 from range-v3/include/range/v3/utility/functional.hpp:16,
                 from range-v3/include/range/v3/utility/iterator_concepts.hpp:23,
                 from range-v3/include/range/v3/utility/iterator_traits.hpp:20,
                 from range-v3/include/range/v3/utility/iterator.hpp:25,
                 from range-v3/include/range/v3/begin_end.hpp:24,
                 from range-v3/include/range/v3/core.hpp:17,
                 from range-v3/include/range/v3/all.hpp:17,
                 from range.cpp:5:
/opt/rh/devtoolset-4/root/usr/include/c++/5.2.1/bits/unique_ptr.h:228:2: note: candidate: template<class _Up, class> std::unique_ptr<_Tp, _Dp>::unique_ptr(std::auto_ptr<_Up>&&)
  unique_ptr(auto_ptr<_Up>&& __u) noexcept;
  ^
/opt/rh/devtoolset-4/root/usr/include/c++/5.2.1/bits/unique_ptr.h:228:2: note:   template argument deduction/substitution failed:
In file included from range-v3/include/range/v3/view.hpp:23:0,
                 from range-v3/include/range/v3/all.hpp:21,
                 from range.cpp:5:
range-v3/include/range/v3/view/any_view.hpp:364:55: note:   mismatched types ‘std::auto_ptr<_Up>’ and ‘ranges::v3::detail::any_view_impl<odd<int>, (ranges::v3::category)0>*’
                     view::all(std::forward<Rng>(rng))}}
                                                       ^
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.2.1/memory:81:0,
                 from range-v3/include/range/v3/utility/functional.hpp:16,
                 from range-v3/include/range/v3/utility/iterator_concepts.hpp:23,
                 from range-v3/include/range/v3/utility/iterator_traits.hpp:20,
                 from range-v3/include/range/v3/utility/iterator.hpp:25,
                 from range-v3/include/range/v3/begin_end.hpp:24,
                 from range-v3/include/range/v3/core.hpp:17,
                 from range-v3/include/range/v3/all.hpp:17,
                 from range.cpp:5:
/opt/rh/devtoolset-4/root/usr/include/c++/5.2.1/bits/unique_ptr.h:205:7: note: candidate: std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = ranges::v3::detail::any_view_interface<int, (ranges::v3::category)0>; _Dp = std::default_delete<ranges::v3::detail::any_view_interface<int, (ranges::v3::category)0> >]
       unique_ptr(unique_ptr&& __u) noexcept
<... more lines ...>
```

### PR DESCRIPTION
**Pull request by CaseyCarter**
when `ConvertibleTo<range_reference_t<Rng>, Ref>()`

The reference type of `any_cursor_impl` and `any_view_impl` must be specified explicitly, and the reference type of the actual iterator / view must convert to the specified type.

Fixes #444.

### CODE REVIEW

**Comment by ericniebler** [comment]
*cough* TESTS *cough*

**Comment by ericniebler** [comment]
The gcc build is crapping out with "inconsistent overrides" warnings. You have to use `override` on all overrides or none.

File: test/view/any_view.cpp [hunk 1]
```diff
@@ -21,34 +22,58 @@
...
+        any_view<int&> e;
+        CHECK(e.begin() == e.begin());
+        CHECK(e.begin() == e.end());
+    }
+    {
+        range_iterator_t<any_random_access_view<int&>> i{},j{};
+        range_sentinel_t<any_random_access_view<int&>> k{};
+        CHECK(i == j);
+        CHECK(i == k);
+        CHECK((i - j) == 0);
```
Comment (CaseyCarter) [inline test/view/any_view.cpp]: Among all the whitespace adjustments, it's easy to miss that this line is new.

**Comment by CaseyCarter** [comment]
Could you please restart https://travis-ci.org/ericniebler/range-v3/jobs/153431000 ?

**Comment by ericniebler** [comment]
Awesome, thanks!
